[pytest]
DJANGO_SETTINGS_MODULE = application.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test* *Tests *TestsCase
python_functions = test_*
addopts = -v --tb=short
testpaths = dvadmin/utils/tests
