# Generated by Django 6.0.3 on 2026-03-08 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("merchants", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序权重")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="books.category",
                        verbose_name="父分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "图书分类",
                "verbose_name_plural": "图书分类",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="书名")),
                ("author", models.CharField(max_length=100, verbose_name="作者")),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=20, verbose_name="ISBN"),
                ),
                (
                    "publisher",
                    models.CharField(blank=True, max_length=100, verbose_name="出版社"),
                ),
                (
                    "publish_date",
                    models.DateField(blank=True, null=True, verbose_name="出版日期"),
                ),
                ("description", models.TextField(blank=True, verbose_name="图书简介")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="book_covers/",
                        verbose_name="封面图片",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="库存")),
                (
                    "warning_stock",
                    models.IntegerField(default=10, verbose_name="预警库存"),
                ),
                ("sales", models.IntegerField(default=0, verbose_name="销售量")),
                (
                    "is_on_sale",
                    models.BooleanField(default=True, verbose_name="是否上架"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="merchants.merchant",
                        verbose_name="所属商家",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="books.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "图书",
                "verbose_name_plural": "图书",
                "ordering": ["-created_at"],
            },
        ),
    ]
